version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "users:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_PORT: "9092"
      KAFKA_BROKER_ID: 100
      KAFKA_LISTENERS: LOCAL://:9092
      KAFKA_ADVERTISED_LISTENERS: LOCAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LOCAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LOCAL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
